train_dir: 'C:\Users\LGESLocalAdmin\Desktop\NFF_valid\IMG_DATA\TRAIN_TEST\TRAIN'
test_dir: 'C:\Users\LGESLocalAdmin\Desktop\NFF_valid\IMG_DATA\TRAIN_TEST\TEST'
save_dir: 'C:\Users\LGESLocalAdmin\Desktop\NFF_valid\models\save'
model_dir: 'C:\Users\LGESLocalAdmin\Desktop\NFF_valid\models\pretrained'
project_name : 'SURFACE_ANODE_DiNO_0727'
model_name : 'vit_small_patch14_dinov2.lvd142m' ## TIMM type
pretrained : 'dino_small.bin' 
head_type : 'transformer'  # transformer | linear | general_gem | effnet_gem | backbone
freeze_backbone : True
finetuning : False ## True, False
finetuning_weight : 'f1_score0.9777_Loss0.0849972_epoch12.pth'
n_classes: 11
img_size: [518, 518]
labels : ['CRACK_1', 'CRACK_2', 'CRACK_FOIL_1', 'CRACK_FOIL_2', 'CRATER_1', 'CRATER_2', 'DEBRIS', 'PROTRUSION_1', 'PROTRUSION_2','PROTRUSION_3', 'SCRATCH_TINY']
valid_ratio : 0.1
datasets_name : "SURFACE_ANODE"
batch_size : 128
num_workers : 12
accumulation_steps : 1
focal_gamma: 2.0
focal_alpha: [1.2, 1.2, 1.5, 1.5, 1., 1., 1., 1., 1., 1., 1.]
token_fusion: "sum" # concat | attn | sum
use_mixup: False   # True
use_cutmix: False  # 둘 중 하나만 True
mixup_alpha: 1.0   # Beta 분포의 alpha (클수록 균등, 작을수록 극단)
use_weighted_sampler: False # True: Sampler | False: Shuffle

## model_name
# convnextv2_base.fcmae_ft_in22k_in1k
# tf_efficientnetv2_m.in21k
# tiny_vit_21m_224
# yolov8x_cls
# vit_small_patch14_dinov2.lvd142m

## datasets
# FTF_FOLDING
# SMW
# LHS
# FTF
# AIA
# SURFACE



